global:
  scrape_interval: 20s 
  evaluation_interval: 20s 
  
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          
rule_files:

scrape_configs:
  - job_name: "prometheus"
 static_configs:
   - targets: ["localhost:9090"]